### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by kelek2** [jbwang1997/BboxToolkit#1]
Hi:
when we use your tool img_split.py,  meet the error TypeError: can't pickle _thread.RLock objects,
happens        " patch_infos = pool.map(worker, zip(infos, img_dirs))" , looks like multiprocessing problem , can you suggest us how to solve the problem， thanks

**Comment by jbwang1997** [comment]
I haven't met this error in my python 3.7.3. I recommend you updating the vision of python or using one processing by setting --nproc 1.

**Comment by kelek2** [comment]
Thank you for your reply, and I would like to ask again. When using FASTER RCNN OBB to train the DOTA dataset, first I want to use the img_split.py tool to cut the image, and whether the input dota txt annotation data format is (x1, x2, y1, y2, x3 ,y3,x4,y4,lable,diff)

**Comment by jbwang1997** [comment]
Yes. img_split.py can directly load DOTA annotations by setting `--load_type dota`. There are also other annotation formats for different datasets.

**Comment by kelek2** [comment]
Thanks, I use img_split.py split the image and make the annotation files, but when we use   FASTER RCNN OBB  method train  the splited  DOTA dataset, run tools/train.py ,
 we meet the problem "ValueError: operands could not be broadcast together with shapes (3,8) (4,) ",
 where it happed in the "mmdet/datasdets/pipelines/transforms.py", 
function"       def _resize_bboxes(self, results):
        """Resize bounding boxes with ``results['scale_factor']``."""
        img_shape = results['img_shape']
        for key in results.get('bbox_fields', []):
            bboxes = results[key] * results['scale_factor']
            bboxes[:, 0::2] = np.clip(bboxes[:, 0::2], 0, img_shape[1])
            bboxes[:, 1::2] = np.clip(bboxes[:, 1::2], 0, img_shape[0])
            results[key] = bboxes"
we think it the train image or annotations format problem, can u give us a brief introdaction how to make the data format to train the DOTA datesets using the  FASTER RCNN OBB,  the config file is "configs/obb/faster_rcnn_obb/faster_rcnn_obb_r50_fpn_1x_dota10.py", thanks!

**Comment by jbwang1997** [comment]
Sorry, this is the first time I meet this error, You can check [oriented_model_starting](https://github.com/jbwang1997/OBBDetection/blob/master/docs/oriented_model_starting.md) for details of using OBBDtection.

**Comment by XuJieLing-cloud** [comment]
@kelek2 have you solved your problem?  i am confused , too
