### ISSUE TITLE
imagesize doesn't support big tiff with head 49492b00

### ISSUE THREAD

**Issue by muranran** [jbwang1997/BboxToolkit#13]
![image](https://github.com/user-attachments/assets/767e1c1c-b79a-4c43-9c6f-e824903ee190)
![image](https://github.com/user-attachments/assets/d4d473e9-eca8-42e9-ae03-5bcf084c7d89)

**Comment by hust-lidelong** [comment]
已收到邮件，谢谢

**Comment by muranran** [comment]
# handle little endian big TIFF
        elif head.startswith(b'\x49\x49\x2B\x00\x08'):
            file = fhandle
            TAG_IMAGE_WIDTH = 256
            TAG_IMAGE_HEIGHT = 257

            # 读取第一个 IFD 偏移位置
            file.seek(8)
            ifd_offset = struct.unpack('<Q', file.read(8))[0]
            
            # 跳到第一个 IFD 位置
            file.seek(ifd_offset)
            
            # 读取 IFD 中的条目数量
            num_entries = struct.unpack('<Q', file.read(8))[0]
            
            # 解析 IFD 条目以找到宽度和高度标签
            width, height = -1, -1
            for _ in range(num_entries):
                tag = struct.unpack('<H', file.read(2))[0]  # 标签 ID
                file.seek(2, 1)  # 跳过字段类型
                file.seek(8, 1)  # 跳过字段计数
                value_offset = struct.unpack('<Q', file.read(8))[0]  # 读取值或值的偏移
                
                # 检查标签 ID 是否为宽度或高度
                if tag == TAG_IMAGE_WIDTH:
                    width = value_offset
                elif tag == TAG_IMAGE_HEIGHT:
                    height = value_offset

                # 如果宽度和高度都找到了，就可以结束搜索
                if width != -1 and height != -1:
                    break

            if width == -1 or height == -1:
                raise ValueError("Invalid TIFF file: width and/or height IDS entries are missing.")
