### ISSUE TITLE
about ODTA1.0 split

### ISSUE THREAD

**Issue by BooKing-hub** [jbwang1997/BboxToolkit#4]
作者您好，我今天发现单独分割train，val分别是9734，5279张图片，但是trainval切割完是12800张图片，这是为什么呢。

**Comment by jbwang1997** [comment]
train 的 filter_empty 为 true，会过滤掉没有目标的 patch。val 因为做测试所以不会开。trainval 也会有 filter_empty 为 true

**Comment by BooKing-hub** [comment]
> train 的 filter_empty 为 true，会过滤掉没有目标的 patch。val 因为做测试所以不会开。trainval 也会有 filter_empty 为 true
明白了，感谢您的解答
